# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-17 14:14
from __future__ import unicode_literals

from django.db import migrations, models
import kidGames.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.DecimalField(decimal_places=1, max_digits=10)),
                ('question_string', models.CharField(blank=True, max_length=120, null=True)),
                ('question_number', models.DecimalField(decimal_places=1, max_digits=10)),
                ('img1', models.ImageField(blank=True, null=True, upload_to=kidGames.models.get_image_path)),
                ('img2', models.ImageField(blank=True, null=True, upload_to=kidGames.models.get_image_path)),
                ('img3', models.ImageField(blank=True, null=True, upload_to=kidGames.models.get_image_path)),
                ('img4', models.ImageField(blank=True, null=True, upload_to=kidGames.models.get_image_path)),
                ('img5', models.ImageField(blank=True, null=True, upload_to=kidGames.models.get_image_path)),
                ('img6', models.ImageField(blank=True, null=True, upload_to=kidGames.models.get_image_path)),
                ('img7', models.ImageField(blank=True, null=True, upload_to=kidGames.models.get_image_path)),
                ('img8', models.ImageField(blank=True, null=True, upload_to=kidGames.models.get_image_path)),
                ('img9', models.ImageField(blank=True, null=True, upload_to=kidGames.models.get_image_path)),
                ('answeer', models.DecimalField(decimal_places=1, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=120, null=True)),
                ('password', models.CharField(blank=True, max_length=120, null=True)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
