# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-17 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kidGames', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answeer',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='category_id',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_number',
            field=models.SmallIntegerField(),
        ),
    ]
