# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-17 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kidGames', '0002_auto_20160417_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_string',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
