# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-17 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kidGames', '0003_auto_20160417_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='img1',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
