# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-18 04:05
from __future__ import unicode_literals

from django.db import migrations, models
import kidGames.models


class Migration(migrations.Migration):

    dependencies = [
        ('kidGames', '0010_auto_20160418_0328'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='background',
            field=models.ImageField(blank=True, null=True, upload_to=kidGames.models.UploadToPathAndRename('static/media/upload/here')),
        ),
    ]
